services:
  - type: web
    name: coqui-tts-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 5002
      - key: TTS_MODEL
        value: tts_models/en/ljspeech/tacotron2-DDC
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /
    disk:
      name: tts-models
      sizeGB: 10
      mountPath: /app/models
